version: 0.0
os: linux

files:
  - source: /
    destination: /code

hooks:
  BeforeInstall:
    - location: aws_scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws_scripts/start_server
      timeout: 3600
  ApplicationStop:
    - location: aws_scripts/stop_server
      runas: root